ci: if the "pnpm install" command fails, retry this command 10 times (#6)
* ci: if the "pnpm install" command fails, retry this command 10 times

    In Node.js 14.0.0, the "pnpm install" command may fail. Therefore, if it fails, retry 10 times

* ci: clear the cache before retrying the "pnpm install" command

* ci: retry the "pnpm install" command every 5 seconds

* ci: clear the `node_modules` before retrying the "pnpm install" command

* ci: may not fail with `pnpm@5.7.0`

    see https://github.com/pnpm/pnpm/issues/3007#issuecomment-759985980

* revert: ci: clear the `node_modules` before retrying the "pnpm install" command

    This reverts commit 64b20ec42ca510c1fcb887372230320f6daf4b8f.

* revert: ci: clear the cache before retrying the "pnpm install" command

    This reverts commit c9d4fa553a4ebfd295a0292dddefdb70866c4bbc.

* ci: no need to wait five seconds

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -70,7 +70,26 @@ jobs:
       - name: Install pnpm
         run: npm i -g pnpm
       - name: Install Dependencies
-        run: pnpm install
+        shell: bash
+        # In Node.js 14.0.0, the "pnpm install" command may fail.
+        # It may not fail with pnpm version 5.7.0.
+        # see https://github.com/pnpm/pnpm/issues/3007#issuecomment-759985980
+        run: |
+          for i in {1..2} ; do
+            if [ ${i} -ne 1 ]; then
+              echo
+              echo '[!]' retry for the second time
+
+              echo '>' npm i -g pnpm@5.7.0
+              npm i -g pnpm@5.7.0
+            fi
+
+            echo '>' pnpm install
+            if pnpm install; then
+              exit $?
+            fi
+          done
+          exit 1
       - run: pnpm run test-only
   complete:
     # see https://github.community/t/status-check-for-a-matrix-jobs/127354/7
