ci(github actions): introduce `madhead/semver-utils` action (#682)
* ci(github actions): introduce `madhead/semver-utils` action

    By using `madhead/semver-utils` action we can use conditions with SemVer range.

* ci(github actions): set the variable `COREPACK_VERSION_RANGE` in another step

* ci(github actions): use `--force` option in Corepack overwrite install

* ci(github actions): fix issues reported by actionlint

    Fixed issues caused by SC2086 rule reported by shellcheck.
    see https://www.shellcheck.net/wiki/SC2086

* ci(github actions): compare `satisfies` output with string "true"

* ci(github action): use conditional expression `"true" == true`

* revert(github actions): ci(github action): use conditional expression `"true" == true`

    This reverts commit e52a4ad91bfde4798a27324d494427448e05e4cd.

* ci(github actions): use conditional expression `!! "true"`

* revert(github actions): ci(github actions): use conditional expression `!! "true"`

    This reverts commit 709edf887d0332c4f0e8bf0ff6500c6241b75307.

* ci(github actions): use conditional expression `"true" && "true" != 'false'`

* ci(github actions): ignore errors when running old Corepack for print to console

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -383,20 +383,11 @@ jobs:
             # This problem started occurring around 2022-06-27.
             # It is probably an issue with the npm registry, as it also started occurring with older pnpm.
         include:
-          # Corepack 0.11.0 and later only supports Node.js 14.14.0 and later
-          # see https://github.com/nodejs/corepack/pull/227
           - node-version: 12.17.0 # minimum version supported by pnpm v6 - https://github.com/pnpm/pnpm/releases/tag/v6.0.0
-            corepack-version-range: "<0.11"
           - node-version: 12.20.0 # minimum version that supports ECMAScript modules - https://nodejs.org/api/esm.html#modules-ecmascript-modules
-            corepack-version-range: "<0.11"
-          - node-version: 12.x
-            corepack-version-range: "<0.11"
           - node-version: 14.1.0 # 14.0.0 excluded, so add the next version 14.1.0
-            corepack-version-range: "<0.11"
           - node-version: 14.13.0 # minimum version that supports ECMAScript modules - https://nodejs.org/api/esm.html#modules-ecmascript-modules
-            corepack-version-range: "<0.11"
           - node-version: 14.13.1 # minimum version that supports "node:" import - https://nodejs.org/api/esm.html#node-imports
-            corepack-version-range: "<0.11"
           - node-version: 14.18.0 # minimum version where the "require()" function supports "node:" import - https://nodejs.org/api/modules.html#core-modules
     steps:
       - uses: actions/checkout@v3
@@ -423,24 +414,38 @@ jobs:
           git config --global user.name  CI
           git config --global user.email dummy@example.com
       - name: Setup Node.js ${{ matrix.node-version }}
+        id: setup-node
         uses: actions/setup-node@v3
         with:
           node-version: ${{ matrix.node-version }}
+      - uses: madhead/semver-utils@v3
+        id: use-old-corepack
+        with:
+          # Instead of using "matrix.node-version", use the "node-version" output of the "actions/setup-node".
+          # Because the value of "matrix.node-version" is not a version. It is a semver range.
+          version: ${{ steps.setup-node.outputs.node-version }}
+          # Corepack 0.11.0 and later only supports Node.js 14.14.0 and later
+          # see https://github.com/nodejs/corepack/pull/227
+          satisfies: <14.14.0
+      - name: Set COREPACK_VERSION_RANGE
+        # see https://github.com/actions/toolkit/issues/1368
+        if: steps.use-old-corepack.outputs.satisfies && steps.use-old-corepack.outputs.satisfies != 'false'
+        shell: bash
+        run: echo 'COREPACK_VERSION_RANGE=<0.11' >> "${GITHUB_ENV}"
       - name: Enable Corepack (Automatically setup a package manager for Node.js)
         shell: bash
-        # If Corepack does not exist or a Corepack version range is specified, install Corepack
+        # If Corepack does not exist or old Corepack is required, install Corepack
         run: |
-          readonly COREPACK_VERSION_RANGE='${{ matrix.corepack-version-range }}'
           if { type corepack >/dev/null 2>&1; } && [ -z "${COREPACK_VERSION_RANGE}" ]; then
             echo Corepack "$(corepack --version)" is already installed
           else
             readonly corepack_package_spec="corepack${COREPACK_VERSION_RANGE:+"@${COREPACK_VERSION_RANGE}"}"
             if type corepack >/dev/null 2>&1; then
-              echo '::group::Override corepack' "(install ${corepack_package_spec})"
+              echo '::group::Overwrite' install "corepack@$(corepack --version || echo '[Execution failed; Version is unknown]')" with "${corepack_package_spec}"
             else
               echo '::group::Install' "${corepack_package_spec}"
             fi
-            npm install --global "${corepack_package_spec}"
+            npm install --global --force "${corepack_package_spec}"
             echo '::endgroup::'
           fi
           echo '::group::$' corepack enable
