ci: check rate limits for the GitHub API (#334)
* ci: check rate limits for the GitHub API

    Occasionally, APIs invoked with the GITHUB_TOKEN secret reach the rate limit and fail.
    In this case, we need to wait until the rate limit resets, but we do not know how long we should wait.
    So, check the rate limit status of the API every time.

* ci: show rate limit status in an easy-to-read format

* ci(github actions): fix shell syntax

* ci(github actions): display an error when the rate limit is reached

* ci(github actions): fix the script for generating rate limit error messages

* ci(github actions): fix the format of rate limit error messages

    + Specifying an easy-to-read format for the `date` command
    + Stop using `title` parameter in workflow commands for error and warning messages

* ci(github actions): show time zone in date to be included in rate limit error messages

* ci(github actions): fix condition for displaying rate limit error messages

    Fix mistakes in conditional statements that were intentionally included for debugging purposes.

* ci(github actions): fix condition for displaying rate limit warning messages

    Fix mistakes in conditional statements that were intentionally included for debugging purposes.

* ci(github actions): display the rate limit reset time in human readable format

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -23,8 +23,32 @@ jobs:
       }}
     runs-on: ubuntu-latest
     steps:
-      # nothing
-      - run: ":"
+      - name: Check GitHub API rate limit
+        shell: bash
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        # https://shogo82148.github.io/blog/2020/10/23/github-bot-using-actions/
+        # https://stackoverflow.com/a/59352240/4907315
+        # https://docs.github.com/ja/actions/learn-github-actions/workflow-commands-for-github-actions
+        run: |
+          readonly DATE_FORMAT='+%Y/%m/%d %T %Z'
+
+          RATE_LIMIT_JSON="$(gh api 'rate_limit')"
+          for type in 'core' 'search' 'graphql' 'integration_manifest' 'source_import' 'code_scanning_upload' 'actions_runner_registration' 'scim' ; do
+            echo '::group::' "${type}"
+            echo "${RATE_LIMIT_JSON}" | jq ".resources.${type}"
+            echo "::notice::Reset time is $(date -ud "@$(echo "${RATE_LIMIT_JSON}" | jq -r ".resources.${type}.reset")" "${DATE_FORMAT}")"
+            echo '::endgroup::'
+          done
+
+          core_remaining="$(echo "${RATE_LIMIT_JSON}" | jq -r ".resources.core.remaining")"
+          if [ "${core_remaining}" == 0 ]; then
+            core_reset="$(echo "${RATE_LIMIT_JSON}" | jq -r ".resources.core.reset")"
+            echo "::error::Rate limit reached. Please wait until $(date -ud "@${core_reset}" "${DATE_FORMAT}")"
+            exit 1
+          elif [ "${core_remaining}" -lt 10 ]; then
+            echo "::warning::The rate limit is approaching: core.remaining=${core_remaining}"
+          fi
   lint:
     needs: if-run-ci
     runs-on: ubuntu-latest
