ci(format): set up dprint in multiple ways

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -64,9 +64,18 @@ jobs:
       - name: Install Dependencies
         run: pnpm install
       - name: Setup dprint
-        # The execution of the dprint command installed from npm will fail only on CI.
-        # So, set up dprint according to the instructions on the official site, and replace the dprint installed from npm.
-        # https://dprint.dev/ci/
+        # The dprint command may fail to deserialize the wasm module.
+        # This only happens on CI, and in some cases no error occurs.
+        # Since we cannot identify the condition under which the error occurred,
+        # we will set up the dprint command in multiple ways and start the next step in a way that does not cause the error.
+        #
+        # 1. Try to run the dprint command installed from npm
+        # 2. If failed, directly execute the dprint binary file extracted in the npm package
+        # 3. If failed, download and set up dprint from the official website.
+        #    The version should be the one we are using in our project.
+        #    see https://dprint.dev/ci/
+        # 4. If failed, download and set up dprint from the official website.
+        #    Without specifying the version, download the latest version of dprint.
         shell: bash
         run: |
           echo '::group::' ls -alp ./node_modules/.bin/dprint
@@ -111,7 +120,24 @@ jobs:
               echo '::endgroup::'
 
               echo '::group::' pnpx dprint '[download from official with version]'
-              pnpx dprint
+              pnpx dprint || {
+                echo '::endgroup::'
+
+                echo '::group::' Install dprint
+                curl -fsSL https://dprint.dev/install.sh | sh -s
+                echo '::endgroup::'
+
+                echo '::group::' mv "${HOME}/.dprint/bin/dprint" ./node_modules/.bin/
+                                mv "${HOME}/.dprint/bin/dprint" ./node_modules/.bin/
+                echo '::endgroup::'
+
+                echo '::group::' ls -alp ./node_modules/.bin/dprint
+                                ls -alp ./node_modules/.bin/dprint
+                echo '::endgroup::'
+
+                echo '::group::' pnpx dprint '[download from official with latest version]'
+                pnpx dprint
+              }
             }
           }
           echo '::endgroup::'
