chore(dprint): use the dprint CLI instead of eslint-plugin-dprint (#116)
* chore: install dprint & add `.dprint.json`

* chore(dprint): porting ESLint's exclusion rules

* chore(dprint): porting the dprint rules defined in `.eslintrc.yaml`

* chore(dprint): add `.dprint.js.json` -  dprint configuration for `*.js` files

* chore(dprint): porting ESLint's exclusion rules

    I forgot to port the directory exclusion rules.

* build(npm-scripts): add dprint to `fmt` and `fmt:*` scripts

* build(lint-staged): use dprint to format `*.js` and `*.ts` files on commit

* chore(deps): remove `eslint-plugin-dprint`

* chore(eslint): install `eslint-config-prettier`

    Disable ESLint rules that conflict with dprint.

    see https://dev.classmethod.jp/articles/eslint-and-prettier/

* chore(eslint): disable `import/order` rules targeted by TypeScript files

    Disable the `import/order` rule in ESLint so that dprint can sort the `import` statement.
    However, dprint will not sort CommonJS-style `require()` statements.
    Therefore, disable this rule only if the target is a TypeScript file.

* style(dprint): format `*.ts` files - Change the sort order of `import` statements

* chore(rename): rename `.dprint.js.json` to `.dprint-js.json`

* ci(format): set up dprint following the instructions on the official site

    The execution of the dprint command installed from npm will fail only on CI.
    So, set up dprint according to the instructions on the official site, and replace the dprint installed from npm.

    see https://dprint.dev/ci/

* ci(format): build the project even when testing the format

    ESLint reported the following error:
    + Unable to resolve path to module '@sounisi5011/stream-transform-from'  import/no-unresolved

* revert: ci(format): set up dprint following the instructions on the official site

    This reverts commit 284b6425668468aaafabae6735d978d168246e87.

* revert revert: ci(format): set up dprint following the instructions on the official site

    This reverts commit cc75ef20887bc42d24c234df9a25ff81bd9d09d1.

* ci(format): instead of downloading dprint, use the binaries generated during installation from npm

* build(dprint): auto generate dprint exclude list from `.eslintignore`

* chore(dprint): update dprint's exclude list

* revert: ci(format): instead of downloading dprint, use the binaries generated during installation from npm

    This reverts commit 72ac4aa37e2c2d8292b482eb8182889e4945f48c.

* ci(format): detect dprint version and install

* ci(format): if dprint fails, retry the setup

* ci(format): set up dprint in multiple ways

* chore(ci): fix indents

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -63,6 +63,85 @@ jobs:
         uses: ./actions/setup-pnpm
       - name: Install Dependencies
         run: pnpm install
+      - name: Setup dprint
+        # The dprint command may fail to deserialize the wasm module.
+        # This only happens on CI, and in some cases no error occurs.
+        # Since we cannot identify the condition under which the error occurred,
+        # we will set up the dprint command in multiple ways and start the next step in a way that does not cause the error.
+        #
+        # 1. Try to run the dprint command installed from npm
+        # 2. If failed, directly execute the dprint binary file extracted in the npm package
+        # 3. If failed, download and set up dprint from the official website.
+        #    The version should be the one we are using in our project.
+        #    see https://dprint.dev/ci/
+        # 4. If failed, download and set up dprint from the official website.
+        #    Without specifying the version, download the latest version of dprint.
+        shell: bash
+        run: |
+          echo '::group::' ls -alp ./node_modules/.bin/dprint
+                           ls -alp ./node_modules/.bin/dprint
+          echo '::endgroup::'
+
+          echo '::group::' pnpx dprint '[npm installed]'
+          pnpx dprint || {
+            echo '::endgroup::'
+
+            echo '::group::' rm -rf ./node_modules/.bin/dprint
+                             rm -rf ./node_modules/.bin/dprint
+            echo '::endgroup::'
+
+            echo '::group::' mv ./node_modules/dprint/dprint ./node_modules/.bin/
+                             mv ./node_modules/dprint/dprint ./node_modules/.bin/
+            echo '::endgroup::'
+
+            echo '::group::' ls -alp ./node_modules/.bin/dprint
+                             ls -alp ./node_modules/.bin/dprint
+            echo '::endgroup::'
+
+            echo '::group::' pnpx dprint '[npm binary]'
+            pnpx dprint || {
+              echo '::endgroup::'
+
+              echo '::group::' Detect dprint version
+              readonly dprintVersion="$(cat ./package.json  | jq -r '.devDependencies.dprint')"
+              echo dprint version':' "${dprintVersion}"
+              echo '::endgroup::'
+
+              echo '::group::' Install dprint
+              curl -fsSL https://dprint.dev/install.sh | sh -s "${dprintVersion}"
+              echo '::endgroup::'
+
+              echo '::group::' mv "${HOME}/.dprint/bin/dprint" ./node_modules/.bin/
+                               mv "${HOME}/.dprint/bin/dprint" ./node_modules/.bin/
+              echo '::endgroup::'
+
+              echo '::group::' ls -alp ./node_modules/.bin/dprint
+                               ls -alp ./node_modules/.bin/dprint
+              echo '::endgroup::'
+
+              echo '::group::' pnpx dprint '[download from official with version]'
+              pnpx dprint || {
+                echo '::endgroup::'
+
+                echo '::group::' Install dprint
+                curl -fsSL https://dprint.dev/install.sh | sh -s
+                echo '::endgroup::'
+
+                echo '::group::' mv "${HOME}/.dprint/bin/dprint" ./node_modules/.bin/
+                                 mv "${HOME}/.dprint/bin/dprint" ./node_modules/.bin/
+                echo '::endgroup::'
+
+                echo '::group::' ls -alp ./node_modules/.bin/dprint
+                                 ls -alp ./node_modules/.bin/dprint
+                echo '::endgroup::'
+
+                echo '::group::' pnpx dprint '[download from official with latest version]'
+                pnpx dprint
+              }
+            }
+          }
+          echo '::endgroup::'
+      - run: pnpm run build-only-packages
       - run: pnpm run fmt-check
       - run: pnpx run-p 'fmt:!(xs)'
       - name: Check changes
