ci(release): check GitHub API rate limits before running release jobs

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -18,6 +18,34 @@ jobs:
         with:
           ignore-private: true
           only-changed-since: latest release
+      - name: Check GitHub API rate limit
+        shell: bash
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          readonly RATE_LIMIT_JSON="$(gh api 'rate_limit')"
+          readonly RATE_LIMIT_JSON_ARRAY="$(echo "${RATE_LIMIT_JSON}" | jq -r '.resources | [.core, .graphql]')"
+          readonly RATE_LIMIT_REMAINING="$(echo "${RATE_LIMIT_JSON_ARRAY}" | jq -r 'map_values(.remaining) | min')"
+          readonly submodules_count="$(echo '${{ steps.interrogate.outputs.result }}' | jq -r '. | length')"
+          readonly needs_remaining="$((submodules_count * 4))"
+
+          echo '::group::RATE_LIMIT_JSON'
+          echo "${RATE_LIMIT_JSON}"
+          echo '::endgroup::'
+          echo '::group::RATE_LIMIT_JSON_ARRAY'
+          echo "${RATE_LIMIT_JSON_ARRAY}"
+          echo '::endgroup::'
+          echo '::group::debug'
+          echo RATE_LIMIT_REMAINING ":${RATE_LIMIT_REMAINING};"
+          echo submodules_count ":${submodules_count};"
+          echo needs_remaining ":${needs_remaining};"
+          echo '::endgroup::'
+
+          if [ "${RATE_LIMIT_REMAINING}" -lt "${needs_remaining}" ]; then
+            readonly RATE_LIMIT_RESET="$(echo "${RATE_LIMIT_JSON_ARRAY}" | jq -r 'map_values(.reset) | max')"
+            echo "::error::Rate limit reached. Please wait until $(date -ud "@${RATE_LIMIT_RESET}" '+%Y/%m/%d %T %Z')"
+            exit 1
+          fi
   release-please:
     runs-on: ubuntu-latest
     needs: submodules-finder
